### ISSUE TITLE
按照readme的操作无法启动项目

### ISSUE THREAD

**Issue by callmeYe** [AnnaSearl/examples-anna-remax-ui#4]
已经执行npm install

```
Error: Cannot find module '@remax/alipay/node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at API.registerAdapterPlugins (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_@remax_cli@2.4.0@@remax\cli\lib\API.js:129:22)
    at buildMini (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_@remax_cli@2.4.0@@remax\cli\lib\build\mini.js:12:9)
    at run (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_@remax_cli@2.4.0@@remax\cli\lib\build\index.js:25:16)
    at Object.build (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_@remax_cli@2.4.0@@remax\cli\lib\build\index.js:35:20)
    at Object.exports.cli.yargs_1.default.scriptName.usage.command [as handler] (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_@remax_cli@2.4.0@@remax\cli\lib\index.js:29:17)
    at Object.runCommand (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_yargs@15.3.1@yargs\lib\command.js:240:40)
    at Object.parseArgs [as _parseArgs] (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_yargs@15.3.1@yargs\yargs.js:1154:41)
    at Object.parse (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_yargs@15.3.1@yargs\yargs.js:627:25)
    at Object.run (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_@remax_cli@2.4.0@@remax\cli\lib\index.js:63:24)
    at Object.<anonymous> (E:\小程序开发\examples-anna-remax-ui-master\node_modules\_remax@2.4.0@remax\bin\remax:2:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anna-remax-ui-examples@1.0.0 dev: `remax build -w -t "alipay"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anna-remax-ui-examples@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PC\AppData\Roaming\npm-cache\_logs\2020-06-09T08_21_10_398Z-debug.log
```

**Comment by AnnaSearl** [comment]
我试了下是好的，是使用npm run dev wechat 或 yarn run dev wechat 启动项目的么

**Comment by callmeYe** [comment]
npm run dev alipay

**Comment by AnnaSearl** [comment]
ali是不行，我已经修复了，用 npm run dev ali 启动

**Comment by AnnaSearl** [comment]
@callmeYe  另外最好看文档，这里的例子可能不是最新的

**Comment by callmeYe** [comment]
我其实是按文档使用tabs组件发现不正常，才想来用用这个示例代码的。

**Comment by AnnaSearl** [comment]
是的，前面没来得及更新文档，不好意思
