### ISSUE TITLE
不能运行例子

### ISSUE THREAD

**Issue by lipeiyan** [AnnaSearl/examples-anna-remax-ui#7]
npm run dev ali 和npm run dev wechat 都报错，不能正常运行

payne@MacBook-Pro examples-anna-remax-ui % npm run dev ali 

> anna-remax-ui-examples@1.0.0 dev /Users/payne/WebstormProjects/examples-anna-remax-ui
> remax build -w -t "ali"

/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

ValidationError: Invalid configuration object. remax has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'notify'. These properties are valid:
   object { turboPages?, pxToRpx?, cwd?, progress?, compressTemplate?, output?, rootDir?, UNSAFE_wechatTemplateDepth?, one?, configWebpack?, plugins? }
    at Object.validate [as default] (/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/schema-utils/dist/validate.js:96:11)
    at Object.getConfig [as default] (/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/@remax/cli/lib/getConfig.js:23:31)
    at Object.build (/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/@remax/cli/lib/build/index.js:49:35)
    at Object.handler (/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/@remax/cli/lib/index.js:27:17)
    at Object.runCommand (/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/yargs/build/lib/yargs.js:584:29)
    at Object.run (/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/@remax/cli/lib/index.js:67:24)
    at Object.<anonymous> (/Users/payne/WebstormProjects/examples-anna-remax-ui/node_modules/remax/bin/remax:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errors: [
    {
      keyword: 'additionalProperties',
      dataPath: '',
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: [Object],
      data: [Object]
    }
  ],
  schema: {
    type: 'object',
    properties: {
      turboPages: [Object],
      pxToRpx: [Object],
      cwd: [Object],
      progress: [Object],
      compressTemplate: [Object],
      output: [Object],
      rootDir: [Object],
      UNSAFE_wechatTemplateDepth: [Object],
      one: [Object],
      configWebpack: [Object],
      plugins: [Object]
    },
    additionalProperties: false
  },
  headerName: 'remax',
  baseDataPath: 'configuration',
  postFormatter: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anna-remax-ui-examples@1.0.0 dev: `remax build -w -t "ali"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the anna-remax-ui-examples@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/payne/.npm/_logs/2020-08-05T15_52_27_793Z-debug.log

**Comment by lipeiyan** [comment]
已经 npm install 了
